"""empty message

Revision ID: b03243c70b92
Revises: 68e09422281b
Create Date: 2022-10-26 12:37:44.899589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03243c70b92'
down_revision = '68e09422281b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('owner', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('sent_to', sa.Integer(), nullable=False))
    op.drop_column('messages', 'owner_id')
    op.drop_column('messages', 'sent_to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent_to_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'sent_to')
    op.drop_column('messages', 'owner')
    # ### end Alembic commands ###
